# Generated by Django 4.1.2 on 2022-10-21 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStrategyFilterMapModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filtermodel')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.strategymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
