# Generated by Django 4.1.2 on 2022-11-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userstrategyfiltermapmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstobuymodel',
            name='date_to_buy',
            field=models.DateTimeField(),
        ),
    ]
