# Generated by Django 4.1.2 on 2022-11-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_stockstobuymodel_date_to_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstobuymodel',
            name='date_to_buy',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
